version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: "rabbitmq"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - fullstack
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  
  web:
    # build: .
    image: alisalim17/youtube-telegram-bot:latest
    container_name: "api"
    env_file:
      - .env
    ports:
      - "4000:4000"
    depends_on:
      - rabbitmq  # Depends on RabbitMQ service
    networks:
      - fullstack
    volumes:
      - .:/usr/src/app
    command: 
      - /bin/sh
      - -c
      - go run . 
volumes:
  rabbitmq_data:  # Volume for RabbitMQ data storage

networks:
  fullstack:
    driver: bridge
